# CPE695 Final Project for Team 1: <br>
**Group Members**: Ronald "Joey" Rupert, Andrew Greensweight, Michael Salek <br><br>
**Problem Statement:** <br>
The quality of AI-generated images has rapidly increased, leading to concerns of authenticity and trustworthiness. The aim of this project is to investigate whether computer vision techniques can effectively detect when images have been generated by AI. By addressing this problem, we can contribute to the development of algorithms that enhance the authenticity verification of images.
<br>
<br>
**Information on Dataset:** <br>
 https://www.kaggle.com/datasets/birdy654/cifake-real-and-ai-generated-synthetic-images
The dataset contains two classes - REAL and FAKE. For REAL, the images are collected from Krizhevsky & Hinton's CIFAR-10 dataset. For the FAKE images, they were generated to be the  equivalent of CIFAR-10 with Stable Diffusion version 1.4.There are 100,000 images for training (50k per class) and 20,000 for testing (10k per class).
<br>

The below code reads in all of the images and resizes them to all be the same size

This utilizes 5000 Fake and 5000 Real images for training and 1500 Fake and 1500 Real for testing

written by Michael Salek

In [1]:
import pandas as pd
import os
from skimage.transform import resize
from skimage.io import imread
import numpy as np
import matplotlib.pyplot as plt

#Creates the target categories
Categories=['FAKE','REAL']
flat_data_arr_train=[] #input array
target_arr_train=[] #output array

#path which contains all of the training images
datadir_train = "C:/Users/Msalek/Documents/Stevens/EE695/Final Project/Code/train"

#Reads in the images from the selected file directory
for i in Categories:
    print(f'loading... training category : {i}')
    path=os.path.join(datadir_train,i)
    for img in os.listdir(path):
        img_array=imread(os.path.join(path,img))
        img_resized=resize(img_array,(150,150,3))
        flat_data_arr_train.append(img_resized.flatten())
        target_arr_train.append(Categories.index(i))
    print(f'loaded training category:{i} successfully')
flat_data_train=np.array(flat_data_arr_train)
target_train=np.array(target_arr_train)
df_train=pd.DataFrame(flat_data_train) #dataframe
df_train['Target']=target_train
x_train=df_train.iloc[:,:-1] #input data
y_train=df_train.iloc[:,-1] #output data

loading... training category : FAKE
loaded training category:FAKE successfully
loading... training category : REAL
loaded training category:REAL successfully


written by Michael Salek

In [2]:
flat_data_arr_test=[] #input array
target_arr_test=[] #output array
#path which contains all of the training images
datadir_test = "C:/Users/Msalek/Documents/Stevens/EE695/Final Project/Code/test"
for i in Categories:
    print(f'loading... test category : {i}')
    path=os.path.join(datadir_test,i)
    for img in os.listdir(path):
        img_array=imread(os.path.join(path,img))
        img_resized=resize(img_array,(150,150,3))
        flat_data_arr_test.append(img_resized.flatten())
        target_arr_test.append(Categories.index(i))
    print(f'loaded test category:{i} successfully')
flat_data_test=np.array(flat_data_arr_test)
target_test=np.array(target_arr_test)
df_test=pd.DataFrame(flat_data_test) #dataframe
df_test['Target']=target_test
x_test=df_test.iloc[:,:-1] #input data
y_test=df_test.iloc[:,-1] #output data

loading... test category : FAKE
loaded test category:FAKE successfully
loading... test category : REAL
loaded test category:REAL successfully


In order to select the best parameters a smaller data set is used to decrease the required run time

This will utilize 500 Fake and 500 Real for the training set and 150 Fake and 150 Real for the test set

written by Michael Salek

In [3]:
Categories_small=['FAKE_small','REAL_small']
flat_data_arr_train_small=[] #input array
target_arr_train_small=[] #output array
#path which contains all of the training images
datadir_train_small = "C:/Users/Msalek/Documents/Stevens/EE695/Final Project/Code/train"
for i in Categories_small:
    print(f'loading... small training category : {i}')
    path=os.path.join(datadir_train_small,i)
    for img in os.listdir(path):
        img_array=imread(os.path.join(path,img))
        img_resized=resize(img_array,(150,150,3))
        flat_data_arr_train_small.append(img_resized.flatten())
        target_arr_train_small.append(Categories_small.index(i))
    print(f'loaded small training category:{i} successfully')
flat_data_train_small=np.array(flat_data_arr_train_small)
target_train_small=np.array(target_arr_train_small)
df_train_small=pd.DataFrame(flat_data_train_small) #dataframe
df_train_small['Target']=target_train_small
x_train_small=df_train_small.iloc[:,:-1] #input data
y_train_small=df_train_small.iloc[:,-1] #output data

loading... small training category : FAKE_small
loaded small training category:FAKE_small successfully
loading... small training category : REAL_small
loaded small training category:REAL_small successfully


written by Michael Salek

In [4]:
flat_data_arr_test_small=[] #input array
target_arr_test_small=[] #output array
#path which contains all of the training images
datadir_test_small = "C:/Users/Msalek/Documents/Stevens/EE695/Final Project/Code/test"
for i in Categories_small:
    print(f'loading... small test category : {i}')
    path=os.path.join(datadir_test_small,i)
    for img in os.listdir(path):
        img_array=imread(os.path.join(path,img))
        img_resized=resize(img_array,(150,150,3))
        flat_data_arr_test_small.append(img_resized.flatten())
        target_arr_test_small.append(Categories_small.index(i))
    print(f'loaded small test category:{i} successfully')
flat_data_test_small=np.array(flat_data_arr_test_small)
target_test_small=np.array(target_arr_test_small)
df_test_small=pd.DataFrame(flat_data_test_small) #dataframe
df_test_small['Target']=target_test_small
x_test_small=df_test_small.iloc[:,:-1] #input data
y_test_small=df_test_small.iloc[:,-1] #output data

loading... small test category : FAKE_small
loaded small test category:FAKE_small successfully
loading... small test category : REAL_small
loaded small test category:REAL_small successfully


The below code prepares the SVM model to select the best parameters using the smaller data set

written by Michael Salek

In [5]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV
param_grid={'C':[0.1,1,10,100],'gamma':[0.0001,0.001,0.1,1],'kernel':['rbf']}
svc=svm.SVC(probability=True)
model_small=GridSearchCV(svc,param_grid,verbose=2)

The below code fits the model utilizing the smaller set of training data utilizing all of the parameter options

written by Michael Salek

In [6]:
x_train_small=df_train_small.iloc[:,:-1] #input data
y_train_small=df_train_small.iloc[:,-1] #output data

x_test_small=df_test_small.iloc[:,:-1] #input data
y_test_small=df_test_small.iloc[:,-1] #output data

model_small.fit(x_train_small,y_train_small)
print('Model training complete')
# model.best_params_ contains the best parameters obtained from GridSearchCV

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] END ....................C=0.1, gamma=0.0001, kernel=rbf; total time= 2.2min
[CV] END ....................C=0.1, gamma=0.0001, kernel=rbf; total time= 2.2min
[CV] END ....................C=0.1, gamma=0.0001, kernel=rbf; total time= 2.1min
[CV] END ....................C=0.1, gamma=0.0001, kernel=rbf; total time= 2.1min
[CV] END ....................C=0.1, gamma=0.0001, kernel=rbf; total time= 2.1min
[CV] END .....................C=0.1, gamma=0.001, kernel=rbf; total time= 2.1min
[CV] END .....................C=0.1, gamma=0.001, kernel=rbf; total time= 2.1min
[CV] END .....................C=0.1, gamma=0.001, kernel=rbf; total time= 2.1min
[CV] END .....................C=0.1, gamma=0.001, kernel=rbf; total time= 2.1min
[CV] END .....................C=0.1, gamma=0.001, kernel=rbf; total time= 2.1min
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time= 2.3min
[CV] END .......................C=0.1, gamma=0.1

Looking at the accuracy on the small test set using the model trained on the small training set

This also shows the best parameters found by GridSearchCV

written by Michael Salek

In [8]:
from sklearn.metrics import accuracy_score
y_pred_small=model_small.predict(x_test_small)
print("The predicted Data is :")
print(y_pred_small)
print("The actual data is:")
print(np.array(y_test_small))
print(f"The small model is {accuracy_score(y_pred_small,y_test_small)*100}% accurate")

print("The best parameters are: ")
print(model_small.best_params_)

The predicted Data is :
[0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 1 0 1 1 1 0 0 0 1
 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0
 0 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0
 1 1 0 1 0 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0 1
 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 0 1 0 1
 1 1 1 1 1 1 0 1 0 0 1 0 0 1 1 1 0 1 0 1 0 1 1 0 0 0 1 1 0 1 1 0 1 1 1 1 0
 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 0 0 0 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1
 1 1 1 1]
The actual data is:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

The below code prepares the SVM model to use the best parameters found on the entire dataset

written by Michael Salek

In [9]:
param_grid={'C':[10],'gamma':[0.0001],'kernel':['rbf']}
svc=svm.SVC(probability=True)
model=GridSearchCV(svc,param_grid,verbose=2)

The below code fits the model utilizing the the full set of training data using the best parameters selected

written by Michael Salek

In [10]:
x_train=df_train.iloc[:,:-1] #input data
y_train=df_train.iloc[:,-1] #output data

x_test=df_test.iloc[:,:-1] #input data
y_test=df_test.iloc[:,-1] #output data

model.fit(x_train,y_train)
print('Model training complete')
# model.best_params_ contains the best parameters obtained from GridSearchCV

Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV] END ....................C=10, gamma=0.0001, kernel=rbf; total time=138.1min
[CV] END ....................C=10, gamma=0.0001, kernel=rbf; total time=130.2min
[CV] END ....................C=10, gamma=0.0001, kernel=rbf; total time=135.6min
[CV] END ....................C=10, gamma=0.0001, kernel=rbf; total time=127.2min
[CV] END ....................C=10, gamma=0.0001, kernel=rbf; total time=131.7min
Model training complete


Look at the accuracy of the model using the test set

written by Michael Salek

In [11]:
y_pred=model.predict(x_test)
print("The predicted Data is :")
print(y_pred)
print("The actual data is:")
print(np.array(y_test))
print(f"The model is {accuracy_score(y_pred,y_test)*100}% accurate")

The predicted Data is :
[0 0 0 ... 1 1 1]
The actual data is:
[0 0 0 ... 1 1 1]
The model is 79.0% accurate


# Loading in the Preprocessed Data

In [16]:
import os
import cv2
import numpy as np
from skimage.io import imread
from skimage.transform import resize
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

#Currently using 5k real and 5k fake images for the training set because it was too much data to upload to Colab
#The test set consists of 1.5k real images and 1.5k fake images
real_folder_0 = "C:/Users/Msalek/Documents/Stevens/EE695/Final Project/Code/train/REAL"
fake_folder_0 = "C:/Users/Msalek/Documents/Stevens/EE695/Final Project/Code/train/FAKE"

test_real_folder = "C:/Users/Msalek/Documents/Stevens/EE695/Final Project/Code/test/REAL"
test_fake_folder = "C:/Users/Msalek/Documents/Stevens/EE695/Final Project/Code/test/FAKE"

def load_images_from_folder(folder):
    images = []
    labels = []
    for filename in os.listdir(folder):
        if filename.endswith(".jpg"):
            image = cv2.imread(os.path.join(folder, filename))
            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # Convert BGR to RGB
            images.append(image)
            labels.append("1" if "REAL" in folder else "0")  # Assign labels based on the folder name
    return images, labels


# Load real images and labels
real_images, real_labels = load_images_from_folder(real_folder_0)

# Load fake images and labels
fake_images, fake_labels = load_images_from_folder(fake_folder_0)

# Combine real and fake images and labels
training_images = np.concatenate((real_images, fake_images), axis=0)
training_labels = np.concatenate((real_labels, fake_labels), axis=0)

# Set a random seed for reproducibility
random_seed = 42

# Shuffle the training set
np.random.seed(random_seed)
shuffle_indices = np.random.permutation(len(training_images))
training_images = training_images[shuffle_indices]
training_labels = training_labels[shuffle_indices]

# Combine the training set
combined_data = list(zip(training_images, training_labels))
#Tuples of images and labels
training_images, training_labels = zip(*combined_data)

#Convert the images and labels back into NumPy arrays for further processing
training_images = np.array(training_images)
training_labels = np.array(training_labels)

# Pre-Processing
Perform geometry augmentation shifts and use a Pre-trained CNN to extract features

In [17]:
from skimage.transform import resize
from sklearn.neighbors import KNeighborsClassifier
import tensorflow.keras.applications as keras_applications
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import accuracy_score

# Define image dimensions
image_size = (32, 32)

# Define the geometry augmentation parameters
augmentation_params = {
    "flip": True,
    "shift_range": 0.2
}

def apply_geometry_augmentations(images, labels, augmentation_params):
    datagen = ImageDataGenerator(
        horizontal_flip=augmentation_params["flip"],
        width_shift_range=augmentation_params["shift_range"],
        height_shift_range=augmentation_params["shift_range"]
    )
    augmented_images = []
    augmented_labels = []
    for image, label in zip(images, labels):
        augmented_images.append(image)
        augmented_labels.append(label)
        if augmentation_params["flip"]:
            flipped_image = cv2.flip(image, 1)
            augmented_images.append(flipped_image)
            augmented_labels.append(label)
        if augmentation_params["shift_range"]:
            shifted_image = datagen.random_transform(image)
            augmented_images.append(shifted_image)
            augmented_labels.append(label)
    return augmented_images, augmented_labels



# Load real images and labels for the test set
test_real_images, test_real_labels = load_images_from_folder(test_real_folder)
test_fake_images, test_fake_labels = load_images_from_folder(test_fake_folder)

# Combine real and fake images and labels for the test set
test_images = np.concatenate((test_real_images, test_fake_images), axis=0)
test_labels = np.concatenate((test_real_labels, test_fake_labels), axis=0)

# Load pre-trained MobileNetV2 model (without the top classifier)
model = keras_applications.MobileNetV2(include_top=False, weights='imagenet', input_shape=(image_size[0], image_size[1], 3))

# Reshape the images to match the input shape of MobileNetV2
reshaped_training_images = []
for image in training_images:
    resized_image = resize(image, image_size)
    reshaped_training_images.append(resized_image)
reshaped_training_images = np.array(reshaped_training_images)

reshaped_test_images = []
for image in test_images:
    resized_image = resize(image, image_size)
    reshaped_test_images.append(resized_image)
reshaped_test_images = np.array(reshaped_test_images)

# Flatten the images to use as input features for the KNN classifier
X_train = reshaped_training_images.reshape(len(reshaped_training_images), -1)
Y_train = training_labels
X_test = reshaped_test_images.reshape(len(reshaped_test_images), -1)
Y_test = test_labels

In [18]:
print("X_train:")
print(X_train[:10])
print("X_test:")
print(X_test[:10])
print("Y_train:")
print(Y_train)
print("Y_test:")
print(Y_test)

X_train:
[[0.41176471 0.42745098 0.3372549  ... 0.03921569 0.03137255 0.03529412]
 [0.29411765 0.29411765 0.24705882 ... 0.42745098 0.45490196 0.38431373]
 [0.99607843 0.99607843 0.99607843 ... 0.62352941 0.61960784 0.64313725]
 ...
 [0.23529412 0.23529412 0.20392157 ... 0.23137255 0.23921569 0.18431373]
 [0.44705882 0.44705882 0.43921569 ... 0.44313725 0.42745098 0.42352941]
 [0.98039216 0.94117647 0.98431373 ... 0.23529412 0.4        0.39215686]]
X_test:
[[9.49019608e-01 9.76470588e-01 9.45098039e-01 ... 7.92156863e-01
  7.13725490e-01 6.19607843e-01]
 [7.68627451e-01 9.41176471e-02 1.39322105e-16 ... 1.21568627e-01
  1.17647059e-01 1.01960784e-01]
 [2.90196078e-01 3.88235294e-01 1.64705882e-01 ... 6.43137255e-01
  4.54901961e-01 4.47058824e-01]
 ...
 [1.56862745e-01 1.56862745e-01 1.09803922e-01 ... 2.74509804e-02
  2.35294118e-02 7.84313725e-03]
 [9.25490196e-01 9.25490196e-01 9.25490196e-01 ... 6.90196078e-01
  8.00000000e-01 7.45098039e-01]
 [5.52941176e-01 6.23529412e-01 7.01960

The below code prepares the SVM model for the preprocessed input to use the best parameters found using the small data set

written by Michael Salek

In [19]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV
param_grid={'C':[10],'gamma':[0.0001],'kernel':['rbf']}
svc=svm.SVC(probability=True)
model_pre=GridSearchCV(svc,param_grid,verbose=2)

The below code fits the model for preprocessed data utilizing the the full set of training data

written by Michael Salek

In [20]:
model_pre.fit(X_train,Y_train)
print('Preprocessed Model training complete')

Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV] END .....................C=10, gamma=0.0001, kernel=rbf; total time= 8.8min
[CV] END .....................C=10, gamma=0.0001, kernel=rbf; total time= 8.9min
[CV] END .....................C=10, gamma=0.0001, kernel=rbf; total time= 8.7min
[CV] END .....................C=10, gamma=0.0001, kernel=rbf; total time= 8.8min
[CV] END .....................C=10, gamma=0.0001, kernel=rbf; total time= 8.6min
Preprocessed Model training complete


Look at the accuracy of the preprocessed model using the test set

written by Michael Salek

In [22]:
from sklearn.metrics import accuracy_score
Y_pred=model_pre.predict(X_test)
print("The predicted Data is :")
print(Y_pred)
print("The actual data is:")
print(np.array(Y_test))
print(f"The model is {accuracy_score(Y_pred,Y_test)*100}% accurate")

The predicted Data is :
['1' '0' '1' ... '0' '1' '0']
The actual data is:
['1' '1' '1' ... '0' '0' '0']
The model is 70.39999999999999% accurate
